<?php
namespace Home\Controller;
use Libs\Upload;
class InvoiceController extends BaseController {
    public function index(){
		if(!IS_POST){
			$invoiceInfo=D("Admin/Invoice")->getAllInvoicesByUserId($_SESSION['userid']);
			$count=count($invoiceInfo);
			$this->assign("invoice_info",$invoiceInfo);
			$this->assign("count",$count);
			$this->assign("rest",10-$count);
			$this->display();
		}else{
			$society=I("post.society");
			$invoice_type=I("post.invoice_type");
			$invoice_content=I("post.invoice_content");
			$pic_data=I("post.pic_data",'','');
			$data=array();
			$data['user_id']=$_SESSION['userid'];
			if(empty($society)){
				if($invoice_type==1){
					exit(json_encode(array("code"=>2,"msg"=>"开票名称不能为空")));
				}else{
					exit(json_encode(array("code"=>3,"msg"=>"统一社会信用代码不能为空")));
				}
			}
			if($invoice_type==1){
				$data['invoice_name']=$society;
			}else{
				$data['invoice_credit']=$society;
				if(!empty($pic_data)){
					$data['invoice_addon']=$pic_data;
				}
			}
			$data['invoice_type_id']=$invoice_type;
			$data['invoice_content_id']=$invoice_content;
			$dataInvoice=I("post.data_invoice");
			if(empty($dataInvoice)){
				$data['invoice_add_time']=time();
				$savedNumber=D("Admin/Invoice")->getInvoiceCountByUserId($_SESSION["userid"]);
				if($savedNumber>=10){
					exit(json_encode(array("code"=>9,"msg"=>"最多保存10条！")));
				}
				$invoiceId=M("Invoice")->add($data);
				if($invoiceId){
					exit(json_encode(array("code"=>4,"msg"=>"添加成功")));
				}else{
					exit(json_encode(array("code"=>5,"msg"=>"添加失败")));
				}
			}else{
				$data['invoice_edit_time']=time();
				$checkKey=session("checkKey");
				if($checkKey!=md5($dataInvoice.$_SESSION["userid"])){
					exit(json_encode(array("code"=>7,"msg"=>"非法操作")));
				}else{
					$res=M("Invoice")->where(array("invoice_id"=>$dataInvoice))->save($data);
					if($res!==false){
						exit(json_encode(array("code"=>4,"msg"=>"更新成功")));
					}else{
						exit(json_encode(array("code"=>9,"msg"=>"更新失败，请稍后重试...")));
					}
				}
			}
		}
	}
	public function edit(){
		$key=I("post.key");
		$id=I("get.id");
		if($key!=md5($id.$_SESSION["userid"])){
			exit(json_encode(array("code"=>5,"msg"=>"非法操作")));
		}
		$info=D("Admin/Invoice")->getInvoiceByInvoiceId($_SESSION["userid"],$id);
		session("checkKey",$key);
		exit(json_encode(array("code"=>6,"msg"=>$info)));
	}
	public function delA(){
		$key=I("post.key");
		$id=I("get.id");
		if($key!=md5($id.$_SESSION["userid"])){
			exit(json_encode(array("code"=>5,"msg"=>"非法操作")));
		}
		$res=D("Admin/Invoice")->delInvoiceByInvoiceId($_SESSION["userid"],$id);
		if(false!==$res){
			exit(json_encode(array("code"=>4,"msg"=>"删除成功")));
		}else{
			exit(json_encode(array("code"=>10,"msg"=>"删除失败，请稍后重试...")));
		}
	}
	public function upload(){
		$upload=new Upload();
		$picInfo=$upload->upload($_FILES['file'],"invoiceAddon",array("pdf","PDF"),5);
		if($picInfo=="上传文件后缀不允许"){
			exit(json_encode(array("code"=>2,"msg"=>"请上传PDF文件")));
		}
		if(trim($picInfo)=="上传文件大小不符！"){
			exit(json_encode(array("code"=>3,"msg"=>"请上传文件大小不超过5M")));
		}
		$maxPic=$upload->create_maximage($picInfo);
		if($res!==false){
			exit(json_encode(array("code"=>0,"msg"=>"上传成功","picPath"=>$maxPic,"fileName"=>$_FILES['file']['name'])));
		}else{
			exit(json_encode(array("code"=>1,"msg"=>"上传失败")));
		}
	}
	public function del(){
		if(!IS_POST){
			exit(json_encode(array("code"=>2,"msg"=>"删除失败，请稍后重试...")));
		}
		$data=I("post.data");
		if(empty($data)){
			exit(json_encode(array("code"=>2,"msg"=>"删除失败，请稍后重试...")));
		}
		$documentRoot=$_SERVER['DOCUMENT_ROOT'];
		$filePath=$documentRoot."/Public/".$data;
		if(file_exists($filePath)){
			@unlink($filePath);
			exit(json_encode(array("code"=>0,"msg"=>"删除成功")));
		}else{
			exit(json_encode(array("code"=>2,"msg"=>"删除失败，请稍后重试...")));
		}
	}
	public function getInvoiceByInvoiceId(){
		if(!IS_POST){
			exit(json_encode(array("code"=>5,"msg"=>"非法操作")));
		}else{
			$dataId=I("post.dataId");
			$info=D("Admin/Invoice")->getInvoiceByInvoiceId($_SESSION["userid"],$dataId);
			exit(json_encode(array("code"=>6,"msg"=>$info)));
		}
	}
}