<?php
namespace Home\Controller;
class LogisticsController extends BaseController {
    public function index(){
		if(!IS_POST){
			$logisticsInfo=D("Admin/Logistics")->getAllLogisticsByUserId($_SESSION['userid']);
			$areaInfo=D("Admin/Area")->getSpecificateAreasByLevel(2);
			$count=count($logisticsInfo);
			
			$countryInfo=M("Country")->select();
			$this->assign("logistics_info",$logisticsInfo);
			$this->assign("area_info",$areaInfo);
			$this->assign("country_info",$countryInfo);
			$this->assign("language",$this->langFlag);
			$this->assign("count",$count);
			$this->assign("rest",10-$count);
			$this->display();
		}else{
			$company=I("post.company");
			if(empty($company)){
				exit(json_encode(array("code"=>10070,"msg"=>"公司名称不能为空！")));
			}
			$receiver=I("post.receiver");
			if(empty($receiver)){
				exit(json_encode(array("code"=>10071,"msg"=>"收货人不能为空！")));
			}
			$phone=I("post.phone");
			if(empty($phone)){
				exit(json_encode(array("code"=>10072,"msg"=>"收货人电话不能为空！")));
			}
			$email=I("post.email");
			if(empty($email)){
				exit(json_encode(array("code"=>10073,"msg"=>"收货人邮箱不能为空！")));
			}
			$country=I("post.country");
			$city=I("post.city");
			$prov=I("post.prov");
			$address=I("post.address");
			if(empty($prov)||empty($city)||empty($address)){
				exit(json_encode(array("code"=>10074,"msg"=>"收货人地址不能为空！")));
			}
			$areaModel=D("Admin/Area");
			$data=array();
			$data['user_id']=$_SESSION['userid'];
			$data['logistics_company_name']=$company;
			$data['logistics_receiver']=$receiver;
			$data['logistics_receiver_phone']=$phone;
			$data['logistics_receiver_email']=$email;
			$data['logistics_country_id']=$country;
			if($this->langFlag==1){
				$data['logistics_country']=M("Country")->where(array("country_id"=>$country))->getField("country_name");
			}else{
				$data['logistics_country']=M("Country")->where(array("country_id"=>$country))->getField("country_name2");
			}
			if($country==1){
				if($this->langFlag==1){
					$data['logistics_province']=$areaModel->getParentAreaNameByAreaId($city);
					$data['logistics_city']=$areaModel->getAreaNameByAreaId($city);
				}else{
					$data['logistics_province']=M("Area")->where(array("area_id"=>$prov))->getField("area_name2");
					$data['logistics_city']=M("Area")->where(array("area_id"=>$city))->getField("area_name2");
				}
				
			}else{
				$data['logistics_province']=$prov;
				$data['logistics_city']=$city;
			}
			$data['logistics_dist']='';
			$data['logistics_address']=$address;
			$dataLogistics=I("post.data_logistics");
			if(empty($dataLogistics)){
				$data['logistics_time']=time();
				$savedNumber=D("Admin/Logistics")->getLogisticsCountByUserId($_SESSION["userid"]);
				if($savedNumber>=10){
					exit(json_encode(array("code"=>10076,"msg"=>"最多保存10条！")));
				}
				$logisticsId=M("Logistics")->add($data);
				if($logisticsId){
					exit(json_encode(array("code"=>10077,"msg"=>"添加成功")));
				}else{
					exit(json_encode(array("code"=>10078,"msg"=>"添加失败")));
				}
			}else{
				$checkKey=session("checkKey");
				if($checkKey!=md5($dataLogistics.$_SESSION["userid"])){
					exit(json_encode(array("code"=>10079,"msg"=>"非法操作")));
				}else{
					$res=M("Logistics")->where(array("logistics_id"=>$dataLogistics))->save($data);
					if($res!==false){
						exit(json_encode(array("code"=>10080,"msg"=>"更新成功")));
					}else{
						exit(json_encode(array("code"=>10081,"msg"=>"更新失败，请稍后重试...")));
					}
				}
			}
		}
	}
	public function edit(){
		$key=I("post.key");
		$id=I("get.id");
		if($key!=md5($id.$_SESSION["userid"])){
			exit(json_encode(array("code"=>10079,"msg"=>"非法操作")));
		}
		$info=D("Admin/Logistics")->getLogisticsInfo($_SESSION["userid"],$id);
		session("checkKey",$key);
		exit(json_encode(array("code"=>10082,"msg"=>$info)));
	}
	public function delA(){
		$key=I("post.key");
		$id=I("get.id");
		if($key!=md5($id.$_SESSION["userid"])){
			exit(json_encode(array("code"=>10079,"msg"=>"非法操作")));
		}
		$res=D("Admin/Logistics")->delLogisticsByLogisticsId($_SESSION["userid"],$id);
		if(false!==$res){
			exit(json_encode(array("code"=>10083,"msg"=>"删除成功")));
		}else{
			exit(json_encode(array("code"=>10084,"msg"=>"删除失败，请稍后重试...")));
		}
	}
	public function getLogisticsByLogisticsId(){
		if(!IS_POST){
			exit(json_encode(array("code"=>5,"msg"=>"非法操作")));
		}else{
			$dataId=I("post.dataId");
			$info=D("Admin/Logistics")->getLogisticsInfo($_SESSION["userid"],$dataId);
			exit(json_encode(array("code"=>6,"msg"=>$info)));
		}
	}
}