<?php
namespace Home\Controller;
use Think\Controller;
use Libs\Verification;
use Libs\Upload;
class RegisterController extends Controller {
    public function index(){
        if(!IS_POST){
			$this->display();
		}else{
			$vcode=I("post.vcode");
			$email=I("post.email");
			$pwd=I("post.pwd");
			$cpwd=I("post.cpwd");
			$verifyCode=new Verification();
			if(!$verifyCode->checkVerify($vcode)){
				exit(json_encode(array("code"=>10010,"info"=>"验证码错误")));
			}
//			if(!preg_match("/^[a-z0-9]+([._\\-]*[a-z0-9])*@([a-z0-9]+[-a-z0-9]*[a-z0-9]+.){1,63}[a-z0-9]+$/",$email)){
//			if(!preg_match("/^[a-zA-Z0-9_.-]+@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.[a-zA-Z0-9]{2,6}/$",$email)){
			if(!preg_match("/^[a-zA-Z0-9]+([._\\-]*[a-zA-Z0-9])*@([a-zA-Z0-9]+[-a-zA-Z0-9]*[a-zA-Z0-9]+.){1,63}[a-zA-Z0-9]+$/",$email)){
				exit(json_encode(array("code"=>10021,"info"=>"邮箱格式不正确")));
			}
			if(strlen($pwd)<6||strlen($pwd)>12||preg_match("/^\d+$/",$pwd)||preg_match("/^[a-zA-Z]+$/",$pwd)){
				exit(json_encode(array("code"=>10022,"info"=>"密码密码必须是6-12位数字和英文混合")));
			}
			if($pwd!=$cpwd){
				exit(json_encode(array("code"=>10023,"info"=>"两次密码不一致")));
			}
			$count=M("User")->where(array("user_email"=>$email))->count();
			if($count>0){
				exit(json_encode(array("code"=>10024,"info"=>"邮箱已被注册")));
			}
			$user_uid=D("Admin/User")->generateRandUID();
			if(empty($user_uid)){
				exit(json_encode(array("code"=>10025,"info"=>"内部错误，请联系管理员进行解决")));
			}
			$user_verify=generateRandCode("all",8);
			$strKey=substr(md5($user_verify),6,6);
			$pwd=md5($strKey.$user_uid.$pwd);
			$data=array(
				"user_uid"=>$user_uid,
				"user_password"=>$pwd,
				"user_verify"=>$user_verify,
				"user_email"=>$email,
				"account_status_id"=>2,
				"grade_id"=>0,
				"user_time"=>time(),
				"last_time"=>time(),
				"current_time"=>time(),
				"last_ip"=>get_client_ip(),
				"current_ip"=>get_client_ip()
			);
			$userId=M("User")->add($data);
			if($userId){
				$rnd=str_replace("=","",base64_encode(md5($user_verify.$user_uid)));
				session("uvu",array($user_verify,$user_uid,$userId));
				// exit(json_encode(array("code"=>10026,"info"=>"注册申请成功，请耐心等待审核通过","url"=>U('Index/index'))));
				exit(json_encode(array("code"=>10026,"info"=>"注册申请成功，请耐心等待审核通过")));				
			}else{
				exit(json_encode(array("code"=>10027,"info"=>"注册失败，请稍后重试...")));
			}
		}
	}
	public function company(){
		if(!IS_POST){
			$uvu=session("uvu");
			$rnd=str_replace("=","",base64_encode(md5($uvu[0].$uvu[1])));
			$rnd2=I("get.rnd");
			if($rnd!=$rnd2){
				exit("非法操作！");
			}
			$time=time();
			session("time",$time);
			
			$langSet=cookie('think_language');
			if(empty($langSet)){
				$langSet="zh-cn";
			}else{
				$langSet=$langSet;
			}
			if(strtolower($langSet)=="zh-cn"){
				$this->langFlag=1;
			}else{
				$this->langFlag=2;
			}
			
			$ruleOrder=M("Config")->where(array("config_name"=>"rule_set_order"))->find();
			$rulePeople=M("Config")->where(array("config_name"=>"rule_set_people"))->find();
			
			$countryInfo=M("Country")->select();
			$this->assign("key2",md5($rnd.$time));
			$this->assign("country_info",$countryInfo);
			$this->assign("rule_order",$ruleOrder);
			$this->assign("rule_people",$rulePeople);
			$this->display();
		}else{
			$uvu=session("uvu");
			$rnd=str_replace("=","",base64_encode(md5($uvu[0].$uvu[1])));
			$time=session("time");
			$key=I("post.key");
			if($key!=md5($rnd.$time)){
				exit(json_encode(array("code"=>10028,"info"=>"非法操作")));
			}
			$company_name=I("post.company_name");
			$contacts=I("post.contacts");
			$phone=I("post.phone");
			//if(empty($phone)||!preg_match("/^(1(([357][0-9])|(47)|(45)|[8][0-9]))\d{8}$/",$phone)){
				//exit(json_encode(array("code"=>10028,"info"=>"手机号码格式不正确")));
			//}
			$website=I("post.website");
			$belong_country=I("post.belong_country");
			$data=array(
				"user_id"=>$uvu[2],
				"company_name"=>$company_name,
				"company_area"=>$belong_country,
				"company_website"=>$website,
				"company_contacts"=>$contacts,
				"company_phone"=>$phone,
				"company_deal_time"=>time()
			);
			$cid=M("Company")->add($data);
			if($cid){
				$uvu=session("uvu");
				session("cid",$cid);
				$rnd=str_replace("=","",base64_encode(md5($uvu[0].$uvu[1].$cid)));
				exit(json_encode(array("code"=>10029,"info"=>"提交成功","url"=>U("Register/license",array("rnd"=>$rnd)))));
			}else{
				exit(json_encode(array("code"=>10030,"info"=>"提交失败，请重试或者联系管理员")));
			}
		}
	}
	public function license(){
		$uvu=session("uvu");
		$cid=session("cid");
		$rnd=str_replace("=","",base64_encode(md5($uvu[0].$uvu[1].$cid)));
		$rnd2=I("get.rnd");
		if($rnd!=$rnd2){
			exit("非法操作！");
		}
		$time=time();
		session("ctime",$time);
		$companyInfo=D("Admin/Company")->getCompanyInfoByCompanyId($cid);
		$dealTime=date("m/d H:m",$companyInfo['company_deal_time']);
		$this->assign("deal_time",$dealTime);
		$this->assign("key",md5($rnd.$time));
		$this->display();
	}
	public function fail(){
		$uuu=session("uuu");
		$rnd=str_replace("=","",base64_encode(md5($uuu[0].$uuu[1])));
		$rnd2=I("get.rnd");
		if($rnd!=$rnd2){
			exit("非法操作！");
		}
		$userId=$uuu[2];
		$companyInfo=D("Admin/Company")->getCompanyInfoByUserId($userId);
		$this->assign("company_info",$companyInfo);
		$this->display();
	}
	public function upload(){
		$category=I("get.category");
		$upload=new Upload();
		$picInfo=$upload->upload($_FILES['file'],$category,array("pdf","PDF"),5);
		if($picInfo=="上传文件后缀不允许"){
			exit(json_encode(array("code"=>2,"msg"=>"请上传PDF文件")));
		}
		if(trim($picInfo)=="上传文件大小不符！"){
			exit(json_encode(array("code"=>3,"msg"=>"请上传文件大小不超过5M")));
		}
		$maxPic=$upload->create_maximage($picInfo);
		$data=array();
		$key='';
		if($category=="taxes"){
			$key='company_taxes';
			$data[]=$maxPic;
		}
		if($category=="license"){
			$key='company_license';
		}
		if($category=="invoice"){
			$key='company_invoice';
		}
		if(empty($key)){
			exit(json_encode(array("code"=>2,"msg"=>"上传失败")));
		}
		$cid=session("cid");
		$companyInfo=D("Admin/Company")->getCompanyInfoByCompanyId($cid);
		if(!empty($companyInfo[$key])){
			$documentRoot=$_SERVER["DOCUMENT_ROOT"];
			$fileName=$documentRoot."/Public/".$companyInfo[$key];
			if(is_file($fileName)){
				@unlink($fileName);
			}
		}
		$data[$key]=$maxPic;
		$res=M("Company")->where(array("company_id"=>$cid))->save($data);
		if($res!==false){
			exit(json_encode(array("code"=>0,"msg"=>"上传成功","picPath"=>"http://".$_SERVER['HTTP_HOST']."/Public/".$maxPic)));
		}else{
			exit(json_encode(array("code"=>1,"msg"=>"上传失败")));
		}
	}
}