<?php
namespace Admin\Controller;
use Think\Controller;
class RoleController extends BaseController {
    public function index(){
		$roleInfo=D("Role")->getAllRole();
		$this->assign("role_info",$roleInfo);
		$this->display();
	}
	public function add(){
		if(!IS_POST){
			$groupInfo=D("Group")->getAllGroup();
			$this->assign("group_info",$groupInfo);
			$this->display();
		}else{
			$roleName=I("post.roleName");
			$group=I("post.group");
			$roleRemark=I("post.roleRemark");
			$roleName=trim($roleName);
			$group=trim($group);
			if(empty($roleName)){
				exit(json_encode(array("code"=>10120,'msg'=>"角色名称不能为空")));
			}
			if(empty($group)){
				exit(json_encode(array("code"=>10121,'msg'=>"没有可以选用的组，请联系管理员")));
			}
			$count=D("Role")->checkRoleByName($roleName);
			if($count>0){
				exit(json_encode(array("code"=>10122,'msg'=>"此角色已经存在，不要重复添加")));
			}
			$data=array(
				"role_name"=>$roleName,
				"role_remark"=>trim($roleRemark),
				"role_create_time"=>time()
			);
			$roleId=M("Role")->add($data);
			if($roleId){
				D("GroupRole")->addGR($group,$roleId);
				exit(json_encode(array("code"=>10123,'msg'=>"添加成功","url"=>U('Role/index'))));
			}else{
				exit(json_encode(array("code"=>10124,'msg'=>"添加失败,请稍后重试...")));
			}
		}
	}
	public function edit(){
		if(!IS_POST){
			$groupInfo=D("Group")->getAllGroup();
			$id=I("get.id");
			$roleInfo=D("Role")->getRoleInfoById($id);
			$this->assign("role_info",$roleInfo);
			$this->assign("group_info",$groupInfo);
			$this->display();
		}else{
			$id=I("post.id");
			$roleName=I("post.roleName");
			$group=I("post.group");
			$roleRemark=I("post.roleRemark");
			$roleName=trim($roleName);
			$group=trim($group);
			if(empty($roleName)){
				exit(json_encode(array("code"=>10120,'msg'=>"角色名称不能为空")));
			}
			if(empty($group)){
				exit(json_encode(array("code"=>10121,'msg'=>"没有可以选用的组，请联系管理员")));
			}
			$roleInfo=D("Role")->getRoleInfoById($id);
			if($roleInfo['role_name']!=$roleName){
				$count=D("Role")->checkRoleByName($roleName);
				if($count>0){
					exit(json_encode(array("code"=>10122,'msg'=>"此角色已经存在，不要重复添加")));
				}
			}
			$data=array(
				"role_name"=>$roleName,
				"role_remark"=>trim($roleRemark)
			);
			$res=M("Role")->where(array('role_id'=>$id))->save($data);
			if($res!==false){
				if($roleInfo['group']!=$group){
					D("GroupRole")->saveGR($group,$id);
				}
				exit(json_encode(array("code"=>10125,'msg'=>"更新成功","url"=>U('Role/index'))));
			}else{
				exit(json_encode(array("code"=>10126,'msg'=>"更新失败,请稍后重试...")));
			}
		}
	}
	public function del(){
		if(!IS_POST){
			exit(json_encode(array("code"=>10127,'msg'=>"非法操作")));
		}else{
			$id=I("get.id");
			$key=I("post.key");
			if(md5($id)!=$key){
				exit(json_encode(array("code"=>10128,'msg'=>"删除失败，请稍后重试...")));
			}
			$res=M("Role")->where(array('role_id'=>$id))->delete();
			if($res!==false){
				D("GroupRole")->delGR($id);
				exit(json_encode(array("code"=>10129,'msg'=>"删除成功","url"=>U('Role/index'))));
			}else{
				exit(json_encode(array("code"=>10128,'msg'=>"删除失败，请稍后重试...")));
			}
		}
	}
}