<?php
namespace Admin\Controller;
use Think\Controller;
class ShipmentController extends BaseController {
    public function index(){
		$shipmentInfo=D("Shipment")->getAllShipment();
		$this->assign("shipment_info",$shipmentInfo);
		$this->display();
	}
	public function add(){
		if(!IS_POST){
			$this->display();
		}else{
			$chineseName=I("post.chineseName");
			$englishName=I("post.englishName");
			$chineseName=trim($chineseName);
			$englishName=trim($englishName);
			if(empty($chineseName)){
				exit(json_encode(array("code"=>10120,'msg'=>"中文名称不能为空")));
			}
			if(empty($englishName)){
				exit(json_encode(array("code"=>10121,'msg'=>"英文名称不能为空")));
			}
			$count=D("Shipment")->checkShipmentByName($chineseName);
			if($count>0){
				exit(json_encode(array("code"=>10122,'msg'=>"此名称已经存在，不要重复添加")));
			}
			$data=array(
				"shi_chinese_name"=>$chineseName,
				"shi_english_name"=>$englishName
			);
			$shipmentId=M("Shipment")->add($data);
			if($shipmentId){
				exit(json_encode(array("code"=>10123,'msg'=>"添加成功","url"=>U('Shipment/index'))));
			}else{
				exit(json_encode(array("code"=>10124,'msg'=>"添加失败,请稍后重试...")));
			}
		}
	}
	public function edit(){
		if(!IS_POST){
			$id=I("get.id");
			$shipmentInfo=D("Shipment")->getShipmentInfoByShipmentId($id);
			$this->assign("shipment_info",$shipmentInfo);
			$this->display();
		}else{
			$id=I("post.id");
			$chineseName=I("post.chineseName");
			$englishName=I("post.englishName");
			$chineseName=trim($chineseName);
			$englishName=trim($englishName);
			if(empty($chineseName)){
				exit(json_encode(array("code"=>10120,'msg'=>"中文名称不能为空")));
			}
			if(empty($englishName)){
				exit(json_encode(array("code"=>10121,'msg'=>"英文名称不能为空")));
			}
			$shipmentInfo=D("Shipment")->getShipmentInfoByShipmentId($id);
			if($shipmentInfo['shi_chinese_name']!=$chineseName){
				$count=D("Shipment")->checkShipmentByName($chineseName);
				if($count>0){
					exit(json_encode(array("code"=>10122,'msg'=>"此名称已经存在，不要重复添加")));
				}
			}
			$data=array(
				"shi_chinese_name"=>$chineseName,
				"shi_english_name"=>$englishName
			);
			$res=M("Shipment")->where(array('shipment_id'=>$id))->save($data);
			if($res!==false){
				exit(json_encode(array("code"=>10125,'msg'=>"更新成功","url"=>U('Shipment/index'))));
			}else{
				exit(json_encode(array("code"=>10126,'msg'=>"更新失败,请稍后重试...")));
			}
		}
	}
	public function del(){
		if(!IS_POST){
			exit(json_encode(array("code"=>10127,'msg'=>"非法操作")));
		}else{
			$id=I("get.id");
			$key=I("post.key");
			if(md5($id)!=$key){
				exit(json_encode(array("code"=>10128,'msg'=>"删除失败，请稍后重试...")));
			}
			$res=M("Shipment")->where(array('shipment_id'=>$id))->delete();
			if($res!==false){
				exit(json_encode(array("code"=>10129,'msg'=>"删除成功","url"=>U('Shipment/index'))));
			}else{
				exit(json_encode(array("code"=>10128,'msg'=>"删除失败，请稍后重试...")));
			}
		}
	}
}